Feature/port fixes
MATRIXXSoftware/go-mdd pull request #19
Opened 2024-08-21 08:00 UTC by tboonIV

- field key decoding/encoding
- blob decoding/encoding
- escape character in string decoding/encoding

2024-08-21 12:15 UTC, lwlee2608 commented on cmdc/value.go
> +	panic("Invalid OctetString digit '" + string(ch) + "'. Valid digits are '0'-'9', 'A'-'F'")
return panic with error

2024-08-21 12:17 UTC, lwlee2608 commented on cmdc/value.go
> +			for i := 1; i < len+1; i++ {
is it possible to put this blob of code into a new private function?

2024-08-22 08:42 UTC, lwlee2608 approved these changes

2024-08-23 02:29 UTC, lwlee2608 requested changes

2024-08-23 02:29 UTC, lwlee2608 commented on cmdc/value.go
> +			next1 := b[i]
out of bound access. example: code will panic with this input `"test\"`

2024-08-23 02:29 UTC, lwlee2608 commented on cmdc/value.go
> +					return string(""), err
just do this:
```go
return "", err
```

2024-08-23 02:29 UTC, lwlee2608 commented on cmdc/value.go
> +				next2 := b[i]
out of bound access again

2024-08-23 02:30 UTC, lwlee2608 commented
replace all 
```
    string("") 
```
to
```
    ""
```

2024-08-23 06:15 UTC, tboonIV commented
> replace all
> 
> ```
>     string("") 
> ```
> 
> to
> 
> ```
>     ""
> ```

updated.

2024-08-23 08:33 UTC, lwlee2608 approved these changes

2024-08-23 08:33 UTC, merged